# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Package Dependencies Download

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

on:
  [workflow_dispatch]




jobs:
  download-dependencies:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip download -r requirements.txt -d pypi-packages; fi
        ls -R pypi-packages
    - name: GIT commit and push all changed files
      env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "GeluKu"
        git config --global user.email "gekko.logic@gmail.com"
        git remote add origin git@github.com:GeluKu/python-nexus-app.git
        git add -A
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
        
        
      
        
